#!/usr/bin/env bash
# Regenerate wiki/index.md from the pages on disk.
# Each entry: link + the first sentence of the page body.
set -u
cd "$(dirname "$0")/.." || exit 1
OUT=wiki/index.md

blurb() {  # first prose sentence after the H1, trimmed to ~110 chars
  awk '
    /^---$/ { fm = !fm; next }
    fm { next }
    /^#/ { seen = 1; next }
    seen && NF && !/^>/ && !/^\|/ && !/^!\[/ {
      line = $0
      gsub(/\[\[([^]|]*)\|/, "", line); gsub(/\[\[/, "", line); gsub(/\]\]/, "", line)
      gsub(/\*\*/, "", line); gsub(/\*/, "", line); gsub(/`/, "", line)
      print line; exit
    }' "$1" | cut -c1-110
}

section() {  # $1 = heading, $2 = dir
  [ -d "$2" ] || return 0
  printf '\n## %s\n\n' "$1" >> "$OUT"
  find "$2" -maxdepth 1 -name '*.md' | LC_ALL=C sort | while IFS= read -r f; do
    n=$(basename "$f" .md)
    printf -- '- [[%s]]: %s\n' "$n" "$(blurb "$f")" >> "$OUT"
  done
}

{
  echo '---'
  echo 'type: map'
  echo 'title: "index"'
  echo 'claim: n/a'
  echo 'canonical: true'
  echo 'tags: [map, meta, catalog]'
  echo "updated: $(date +%Y-%m-%d)"
  echo '---'
  echo
  echo '# index'
  echo
  echo 'Catalog of every page in this wiki. Generated by `tools/build-index.sh`. Edit the'
  echo 'pages, not this file.'
  echo
  echo 'New here? Start at [[Overview]]. What is ruled: [[Rulings]]. What waits on Ammon:'
  echo '[[Open Questions]]. Where the job stands: [[Work Plan]]. The book in reading order:'
  echo '[[Section Map]].'
  echo
  printf -- '_%s pages, rebuilt %s_\n' "$(find wiki -name '*.md' | wc -l | tr -d ' ')" "$(date +%Y-%m-%d)"
} > "$OUT"

printf '\n## Maps and entry points\n\n' >> "$OUT"
for n in Overview Rulings "Open Questions" "Work Plan" "Section Map" Records log; do
  [ -f "wiki/$n.md" ] && printf -- '- [[%s]]: %s\n' "$n" "$(blurb "wiki/$n.md")" >> "$OUT"
done

section "Sources" wiki/sources
section "Sections, in recovered-draft order" wiki/sections
section "Concepts" wiki/concepts
section "Threads" wiki/threads

echo "wrote $OUT ($(grep -c '^- ' "$OUT") entries)"
